# Generated by Django 5.1.4 on 2025-01-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_description_1_product_description_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
    ]
